name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare lowercase repo and user
        id: prep
        run: |
          echo "REPO_NAME_LC=$(echo ${GITHUB_REPOSITORY##*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "USER_NAME_LC=$(echo ${GITHUB_ACTOR} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.USER_NAME_LC }}/${{ env.REPO_NAME_LC }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.USER_NAME_LC }}/${{ env.REPO_NAME_LC }}:latest .
      
      - name: Show environment variables
        run: env
